import { z } from "zod";

export const clientSchema = z.object({
  firstName: z.string().min(2).max(80),
  lastName: z.string().min(2).max(80),
  phone: z.string().optional(),
  email: z.string().email().optional().or(z.literal("")),
  minBudget: z.coerce.number().min(0),
  maxBudget: z.coerce.number().positive(),
  currency: z.enum(["USD", "ARS"]).default("USD"),
  desiredTypes: z.array(z.enum(["CASA", "DEPARTAMENTO", "TERRENO", "CAMPO", "LOCAL", "OFICINA", "CABANA", "GALPON"])).min(1),
  desiredCities: z.string().min(2),
  financingNeeded: z.coerce.boolean().default(false),
  financingPercent: z.coerce.number().int().min(0).max(100).optional(),
  hasTrade: z.coerce.boolean().default(false),
  tradePercent: z.coerce.number().int().min(0).max(100).optional(),
  needsCredit: z.coerce.boolean().default(false),
  minMatchThreshold: z.coerce.number().int().min(0).max(100).default(70),
  bedrooms: z.coerce.number().int().min(0).optional(),
  bathrooms: z.coerce.number().int().min(0).optional(),
  minTotalArea: z.coerce.number().min(0).optional(),
  luz: z.string().optional(),
  agua: z.string().optional(),
  gas: z.string().optional(),
  conectividad: z.string().optional(),
  constructionTypes: z.string().optional(),
  pool: z.string().optional(),
  garage: z.string().optional(),
  neighborhoodType: z.string().optional(),
  access: z.string().optional(),
  soilAptitude: z.string().optional(),
  minHectares: z.coerce.number().min(0).optional(),
  maxHectares: z.coerce.number().min(0).optional(),
});
