import { z } from "zod";

export const propertySchema = z.object({
  title: z.string().min(4).max(140),
  cadastralId: z.string().min(2).max(80),
  type: z.enum(["CASA", "DEPARTAMENTO", "TERRENO", "CAMPO", "LOCAL", "OFICINA", "CABANA", "GALPON"]),
  price: z.coerce.number().positive(),
  currency: z.enum(["USD", "ARS"]).default("USD"),
  address: z.string().min(5),
  province: z.string().optional(),
  department: z.string().optional(),
  city: z.string().min(2),
  neighborhood: z.string().optional(),
  description: z.string().optional(),
  documentation: z.string().optional(),
  financing: z.coerce.boolean().default(false),
  financingPercent: z.coerce.number().int().min(0).max(100).optional(),
  acceptsTrade: z.coerce.boolean().default(false),
  tradePercent: z.coerce.number().int().min(0).max(100).optional(),
  luz: z.enum(["RED","SOLAR","GENERADOR","SIN_SERVICIO",]).optional(),
  agua: z.enum(["RED","POZO","VERTIENTE","SIN_SERVICIO",]).optional(),
gas: z.enum(["RED","GARRAFA","ZEPPELIN","SIN_SERVICIO",]).optional(),
conectividad: z.enum(["FIBRA","CABLE", "4G_5G","SATELITAL","SIN_SERVICIO",]).optional(),
  bedrooms: z.coerce.number().int().min(0).optional(),
  bathrooms: z.coerce.number().int().min(0).optional(),
  coveredArea: z.coerce.number().min(0).optional(),
  totalArea: z.coerce.number().min(0).optional(),
  creditReady: z.coerce.boolean().default(false),
  pool: z.coerce.boolean().default(false),
  garage: z.coerce.boolean().default(false),
  neighborhoodType: z.enum(["CENTRO","BARRIO_ABIERTO","BARRIO_CERRADO","COUNTRY","PRIVADO",]).optional(),
  access: z.enum([ "ASFALTO", "RIPIO", "TIERRA",]).optional(),
  constructionTypes: z.enum(["TRADICIONAL","STEEL_FRAME","WOOD_FRAME","SECO","MIXTO",]).optional(),
  generalState: z.enum([ "EXCELENTE","MUY_BUENO","BUENO","A_REFACCIONAR", ]).optional(),
  soilAptitude: z.string().optional(),
  hectares: z.coerce.number().min(0).optional(),
});
