import { z } from "zod";

export const propertySchema = z.object({
  title: z.string().min(4).max(140),
  cadastralId: z.string().min(2).max(80),
  type: z.enum(["CASA", "DEPARTAMENTO", "TERRENO", "CAMPO", "LOCAL", "OFICINA", "CABANA", "GALPON"]),
  price: z.coerce.number().positive(),
  currency: z.enum(["USD", "ARS"]).default("USD"),
  address: z.string().min(5),
  city: z.string().min(2),
  neighborhood: z.string().optional(),
  description: z.string().optional(),
  documentation: z.string().optional(),
  financing: z.coerce.boolean().default(false),
  financingPercent: z.coerce.number().int().min(0).max(100).optional(),
  acceptsTrade: z.coerce.boolean().default(false),
  tradePercent: z.coerce.number().int().min(0).max(100).optional(),
  luz: z.string().optional(),
  agua: z.string().optional(),
  gas: z.string().optional(),
  conectividad: z.string().optional(),
  bedrooms: z.coerce.number().int().min(0).optional(),
  bathrooms: z.coerce.number().int().min(0).optional(),
  coveredArea: z.coerce.number().min(0).optional(),
  totalArea: z.coerce.number().min(0).optional(),
  creditReady: z.coerce.boolean().default(false),
  pool: z.coerce.boolean().default(false),
  garage: z.coerce.boolean().default(false),
  neighborhoodType: z.string().optional(),
  access: z.string().optional(),
  constructionTypes: z.string().optional(),
  generalState: z.string().optional(),
  soilAptitude: z.string().optional(),
  hectares: z.coerce.number().min(0).optional(),
});
